dependencies {
    implementation(project(":shared-kernel"))
    implementation(project(":order"))
    implementation(project(":catalog"))
    implementation(project(":pricing"))
    implementation(project(":decomposition"))
    implementation(project(":reconciliation"))
    implementation(project(":configuration"))
    implementation(project(":audit"))
    implementation(project(":ledger"))
    implementation(project(":settlement"))
    implementation(project(":provider"))
    api("org.springframework.boot:spring-boot-starter-data-jpa")
    api("org.springframework.boot:spring-boot-starter-security")
}
